###########################################################################
# SonarQube properties - required by GitHub Action plugin:
# SonarSource/sonarqube-scan-action@v5
#  Free Rubens Gomes GitHub Org / Projects
# Key: rubensgomes-org
sonar.host.url=https://sonarcloud.io
sonar.organization=rubensgomes-org
sonar.projectName=math-ai-agent
sonar.projectKey=rubensgomes-org
sonar.qualitygate.wait=true
sonar.sources=src
# SONAR_TOKEN must be defined as an environment variable
